window:
  padding:
    x: 2
    y: 2

font:
  size: 11.0

draw_bold_text_with_bright_colors: false

colors:
  primary:
    background: '#{color/background/hex}'
    foreground: '#{color/foreground/hex}'
  selection:
    text:       '#{color/background/hex}'
    background: '#{color/foreground/hex}'
  normal:
    black:   '#{color/black/hex}'
    red:     '#{color/red/hex}'
    green:   '#{color/green/hex}'
    yellow:  '#{color/yellow/hex}'
    blue:    '#{color/blue/hex}'
    magenta: '#{color/magenta/hex}'
    cyan:    '#{color/cyan/hex}'
    white:   '#{color/white/hex}'
  bright:
    black:   '#{color/brblack/hex}'
    red:     '#{color/brred/hex}'
    green:   '#{color/brgreen/hex}'
    yellow:  '#{color/bryellow/hex}'
    blue:    '#{color/brblue/hex}'
    magenta: '#{color/brmagenta/hex}'
    cyan:    '#{color/brcyan/hex}'
    white:   '#{color/brwhite/hex}'
